"""Bundle-only Section 2b Barres / Allen / BrainRNASeq brain expression.

Owns Allen HumanMA microarray (probe_lookup + per-probe expression), Allen
two-donor RNA-seq TPM ZIPs, and BrainRNASeq human/mouse CSV downloads. Not
wired through generic Allen/BrainRNASeq clients when Section 2b is selected.
"""

from __future__ import annotations

import hashlib
import io
import logging
import math
import statistics
import time
from dataclasses import dataclass
from datetime import datetime, timezone
from typing import Any, Sequence

from gene_dossier.config import Settings, get_settings
from gene_dossier.models import (
    AssertionType,
    EvidenceGrade,
    EvidenceRecord,
    SourceCoverageResult,
    SourceStatus,
    SourceType,
    ToolResult,
)
from gene_dossier.section_1c import (
    _append_evidence,
    _persist_artifact_bytes,
    _persist_tool_result_json,
    _save_api_run_failure,
    _tool_result_to_api_run,
    _validate_nonblank_image,
)
from gene_dossier.source_ids import make_source_id, slugify
from gene_dossier.species_identity import fetch_species_identity_results
from gene_dossier.tools import allen_brain, allen_human_rnaseq, brainrnaseq
from gene_dossier.workflow import DossierState, WorkflowTransientContext

logger = logging.getLogger(__name__)

SECTION_EXPRESSION = "Tissue and cell expression"
SUBSECTION_2B = "Barres Lab RNA-Seq brain specific expression data"

BRAINRNASEQ_HOME_URL = "https://brainrnaseq.org/"
NOT_DETERMINED = "not determined"
CATEGORY_NOTE = (
    "Human and mouse brain expression categories were not determined "
    "(threshold policy unresolved)."
)

PLOT_VERSION = "section_2b_celltype_fpkm_v2"
HUMAN_BAR_COLOR = "#F4A6A6"
MOUSE_BAR_COLOR = "#6BA3D9"
FIGURE_FIGSIZE = (7.1, 5.8)
UNAVAILABLE_PANEL_MESSAGE_HUMAN = "Human BrainRNASeq data temporarily unavailable"
UNAVAILABLE_PANEL_MESSAGE_MOUSE = "Mouse BrainRNASeq data temporarily unavailable"
BRAINRNASEQ_SOURCE_LINK_LABEL = "Brain RNA-Seq generated by the Ben Barres lab (Link)"

# Tokens that must never appear as production hardcodes / gold copies.
# Gene symbols (validation genes) are enforced by tests scanning sources;
# this frozenset covers gold filenames / numeric literals only.
SECTION_2B_PRODUCTION_DENYLIST: frozenset[str] = frozenset(
    {
        "image-45fc289b",
        "image-3a4d95af",
        "image-a5c6889b",
        "closest-to-gold",
        "7.023964492",
        "176.6800531",
        "199.8909211",
    }
)

# Ordered display groups for the combined cell-type figure.
HUMAN_CELLTYPE_GROUPS: tuple[tuple[str, tuple[str, ...]], ...] = (
    ("Astrocytes Fetal", ("astrocytes_fetal_",)),
    ("Astrocytes Mature", ("astrocytes_mature_",)),
    ("Neurons", ("neurons_",)),
    ("Oligodendrocytes", ("oligodendrocytes_",)),
    ("Endothelial", ("endothelial_",)),
    ("Microglia", ("microglia_", "microglla_")),
)
MOUSE_CELLTYPE_GROUPS: tuple[tuple[str, tuple[str, ...]], ...] = (
    ("Astrocytes", ("astrocytes_",)),
    ("Neurons", ("neurons_",)),
    ("OPC", ("opc_",)),
    ("Newly Formed Oligodendrocyte", ("newly_formed_oligodendrocyte_",)),
    ("Myelinating Oligodendrocyte", ("myelinating_oligodendrocyte_",)),
    ("Endothelial", ("endothelial_",)),
    ("Microglia/Macrophage", ("microglia_macrophage_", "microglla_")),
)

# Non-expression summary / metadata columns (never treated as replicates).
_SUMMARY_COLUMN_NAMES = frozenset(
    {
        "gene_id",
        "id",
        "gene",
        "symbol",
        "entrez",
        "entrez_id",
        "annotation",
        "description",
    }
)

# Documented matrix policy when a non-target gene cell is unusable in a column.
_MOUSE_TPM_MALFORMED_ROW_POLICY = "skip_malformed_gene_rows_from_denominator"


@dataclass(frozen=True)
class Section2bConfig:
    donor_well_known_file_ids: tuple[int, ...] = (
        allen_human_rnaseq.DEFAULT_DONOR_WELL_KNOWN_FILE_IDS
    )
    exclude_rnaseq_technical_replicates: bool = True
    allen_probe_id: int | None = None
    probe_selection_policy: str = "explicit_or_single_probe"
    category_policy: str = "threshold_policy_unresolved"
    plot_dpi: int = 180
    max_expression_attempts: int = allen_brain.DEFAULT_MAX_EXPRESSION_ATTEMPTS
    retry_sleep_seconds: float = allen_brain.DEFAULT_RETRY_SLEEP_SECONDS

    def __post_init__(self) -> None:
        if tuple(self.donor_well_known_file_ids) != tuple(
            allen_human_rnaseq.DEFAULT_DONOR_WELL_KNOWN_FILE_IDS
        ):
            raise ValueError(
                "Section 2b requires donor IDs "
                f"{allen_human_rnaseq.DEFAULT_DONOR_WELL_KNOWN_FILE_IDS!r}; "
                f"got {self.donor_well_known_file_ids!r}"
            )
        if self.probe_selection_policy not in {
            "explicit_or_single_probe",
            "unresolved",
        }:
            raise ValueError(
                f"Unsupported probe_selection_policy: {self.probe_selection_policy!r}"
            )
        if self.category_policy != "threshold_policy_unresolved":
            raise ValueError(
                f"Unsupported category_policy: {self.category_policy!r}"
            )
        if self.allen_probe_id is not None and int(self.allen_probe_id) <= 0:
            raise ValueError("allen_probe_id must be a positive integer when set")
        if int(self.plot_dpi) < 72:
            raise ValueError("plot_dpi must be >= 72")
        if int(self.max_expression_attempts) < 1:
            raise ValueError("max_expression_attempts must be >= 1")


def section_2b_intro_text(gene_symbol: str = "") -> str:
    gene = (gene_symbol or "").strip() or "gene"
    return (
        "Expression data from Allen Brain Atlas and Barres Lab RNA-Seq were "
        "downloaded, and average expression levels were calculated. The "
        f"{gene} expression results are presented in the table below."
    )


def section_2b_celltype_intro_text(gene_symbol: str = "") -> str:
    gene = (gene_symbol or "").strip() or "gene"
    return (
        f"Additionally, relative {gene} RNA expression in various cell types "
        "isolated from human and mouse brain as measured by RNA-Seq is shown "
        "here, where FPKM is Fragments Per Kilobase Million, a normalization "
        "unit commonly utilized in this type of assay (Barres Lab Brain RNA-Seq)."
    )


def classify_expression(_value: float | None) -> None:
    """Categories stay unresolved until an explicit threshold policy exists."""
    return None


def format_numeric_cell(value: float | None, *, digits: int = 8) -> str:
    if value is None or not math.isfinite(float(value)):
        return NOT_DETERMINED
    text = f"{float(value):.{digits}f}".rstrip("0").rstrip(".")
    return text or "0"


def _normalize_entrez_gene_id(value: Any) -> str | None:
    if value is None or isinstance(value, bool):
        return None
    text = str(value).strip()
    if not text or not text.isdigit():
        return None
    return str(int(text))


def _evidence(
    *,
    dossier_run_id: str,
    gene_symbol: str,
    source_name: str,
    fact_type: str,
    key: str,
    value: dict[str, Any],
    display_text: str,
    api_run_id: str | None = None,
    raw_artifact_id: str | None = None,
    organism: str = "Homo sapiens",
    taxon_id: int = 9606,
    confidence_notes: str | None = None,
) -> EvidenceRecord:
    return EvidenceRecord(
        source_id=make_source_id(source_name, gene_symbol, AssertionType.expression, key),
        dossier_run_id=dossier_run_id,
        gene_symbol=gene_symbol,
        official_symbol=gene_symbol,
        section=SECTION_EXPRESSION,
        subsection=SUBSECTION_2B,
        source_name=source_name,
        source_type=SourceType.expression_database,
        assertion_type=AssertionType.expression,
        fact_type=fact_type,
        organism=organism,
        taxon_id=taxon_id,
        evidence_grade=EvidenceGrade.B,
        value=value,
        display_text=display_text,
        api_run_id=api_run_id,
        raw_artifact_id=raw_artifact_id,
        confidence_notes=confidence_notes,
    )


def _validate_bytes(content: bytes, *, media_type: str) -> dict[str, Any]:
    return {"media_type": media_type, "byte_size": len(content)}


def _persist_tool_result_bytes(
    *,
    tr: ToolResult,
    dossier_run_id: str,
    gene_symbol: str,
    settings: Settings,
    persist_db: bool,
    filename_hint: str,
    extension: str,
    media_type: str,
    content: bytes,
    notes: dict[str, Any] | None = None,
) -> tuple[Any, dict[str, Any] | None]:
    api = _tool_result_to_api_run(tr, dossier_run_id=dossier_run_id, gene_symbol=gene_symbol)
    if not tr.success:
        _save_api_run_failure(api, persist_db=persist_db)
        return api, None
    artifact, meta = _persist_artifact_bytes(
        dossier_run_id=dossier_run_id,
        source_name=tr.source_name,
        content=content,
        extension=extension,
        artifact_type=extension,
        filename_hint=filename_hint,
        settings=settings,
        api_run=api,
        persist_db=persist_db,
        notes={
            "artifact_class": "external_raw",
            "artifact_origin": f"{tr.source_name.lower()}_{tr.endpoint_name}",
            "artifact_role": tr.endpoint_name,
            "source_url": tr.request_url,
            "retrieval_method": "http_bytes",
            **(notes or {}),
        },
        validate=lambda b: _validate_bytes(b, media_type=media_type),
    )
    _ = artifact
    return api, meta


def _mean_expression_level(
    payload: Any,
    *,
    gene_symbol: str | None = None,
    entrez_gene_id: str | None = None,
) -> dict[str, Any]:
    """Extract finite expression_level mean from one microarray_expression payload."""
    if not isinstance(payload, dict):
        return {"success": False, "error_type": "invalid_payload"}
    msg = payload.get("msg")
    if not isinstance(msg, dict):
        return {"success": False, "error_type": "missing_msg"}
    probes = msg.get("probes")
    samples = msg.get("samples")
    if not isinstance(probes, list) or not probes:
        return {"success": False, "error_type": "missing_probes"}
    if not isinstance(samples, list):
        return {"success": False, "error_type": "missing_samples"}
    probe = probes[0]
    if not isinstance(probe, dict):
        return {"success": False, "error_type": "invalid_probe"}
    # Optional identity gate from expression payload when lookup omitted gene fields.
    symbol_target = (gene_symbol or "").strip().lower()
    expr_symbol = str(
        probe.get("gene-symbol") or probe.get("gene_symbol") or ""
    ).strip().lower()
    if symbol_target and expr_symbol and expr_symbol != symbol_target:
        return {
            "success": False,
            "error_type": "expression_symbol_mismatch",
            "expected": symbol_target,
            "got": expr_symbol,
        }
    expected_entrez = _normalize_entrez_gene_id(entrez_gene_id)
    expr_entrez = _normalize_entrez_gene_id(
        probe.get("entrez-id")
        or probe.get("entrez_id")
        or probe.get("gene-entrez-id")
    )
    if expected_entrez is not None and expr_entrez is not None:
        if expected_entrez != expr_entrez:
            return {
                "success": False,
                "error_type": "expression_entrez_mismatch",
                "expected": expected_entrez,
                "got": expr_entrez,
            }
    levels = probe.get("expression_level")
    if not isinstance(levels, list):
        return {"success": False, "error_type": "missing_expression_level"}
    if len(levels) != len(samples):
        return {
            "success": False,
            "error_type": "expression_level_length_mismatch",
            "expression_level_len": len(levels),
            "sample_count": len(samples),
        }
    values: list[float] = []
    for raw in levels:
        try:
            number = float(raw)
        except (TypeError, ValueError):
            return {"success": False, "error_type": "non_numeric_expression_level"}
        if not math.isfinite(number):
            return {"success": False, "error_type": "non_finite_expression_level"}
        values.append(number)
    return {
        "success": True,
        "probe_id": probe.get("id"),
        "mean_expression": float(statistics.mean(values)) if values else None,
        "sample_count": len(values),
        "expression_level": values,
        "gene_symbol": probe.get("gene-symbol") or probe.get("gene_symbol"),
        "entrez_id": expr_entrez,
    }


def validate_probe_lookup_rows(
    probe_payload: Any,
    *,
    gene_symbol: str,
    entrez_gene_id: str | None,
) -> dict[str, Any]:
    """Validate complete HumanMA probe list (no truncation).

    Allen probe_lookup may return only ``id``/``name`` even when gene fields are
    requested. In that case every discovered probe ID is treated as a candidate
    (lookup criteria already filter by gene acronym); symbol/Entrez are gated
    later from each microarray_expression payload.
    """
    if not isinstance(probe_payload, dict):
        return {
            "success": False,
            "discovered_probes": [],
            "validated_probes": [],
            "error_type": "invalid_probe_lookup",
        }
    msg = probe_payload.get("msg")
    if not isinstance(msg, list):
        return {
            "success": False,
            "discovered_probes": [],
            "validated_probes": [],
            "error_type": "missing_probe_list",
        }
    symbol_target = (gene_symbol or "").strip().lower()
    expected_entrez = _normalize_entrez_gene_id(entrez_gene_id)
    discovered: list[dict[str, Any]] = []
    validated: list[dict[str, Any]] = []
    gene_fields_present = False
    for row in msg:
        if not isinstance(row, dict):
            continue
        summary = allen_brain.summarize_probe(row)
        discovered.append(summary)
        pid = summary.get("id")
        try:
            probe_id = int(pid)
        except (TypeError, ValueError):
            continue
        acronym = str(summary.get("gene_acronym") or "").strip().lower()
        probe_entrez = _normalize_entrez_gene_id(summary.get("entrez_id"))
        if acronym or probe_entrez is not None:
            gene_fields_present = True
            if acronym and acronym != symbol_target:
                continue
            if expected_entrez is not None and probe_entrez is not None:
                if probe_entrez != expected_entrez:
                    continue
        validated.append({**summary, "id": probe_id})
    return {
        "success": True,
        "discovered_probes": discovered,
        "validated_probes": validated,
        "discovered_probe_count": len(discovered),
        "validated_probe_count": len(validated),
        "gene_fields_present": gene_fields_present,
    }


def select_agilent_probe(
    validated_probes: Sequence[dict[str, Any]],
    *,
    allen_probe_id: int | None,
    policy: str = "explicit_or_single_probe",
) -> dict[str, Any]:
    """Select probe: explicit CLI id, else single valid probe, else unresolved."""
    ids = []
    for row in validated_probes:
        try:
            ids.append(int(row["id"]))
        except (TypeError, ValueError, KeyError):
            continue
    unique_ids = list(dict.fromkeys(ids))
    if allen_probe_id is not None:
        explicit = int(allen_probe_id)
        if explicit not in unique_ids:
            return {
                "status": "probe_policy_unresolved",
                "policy": policy,
                "selected_probe_id": None,
                "reason": "explicit_probe_not_in_validated_set",
                "explicit_probe_id": explicit,
                "candidate_probe_ids": unique_ids,
            }
        return {
            "status": "selected",
            "policy": "explicit_or_single_probe",
            "selected_probe_id": explicit,
            "reason": "explicit_allen_probe_id",
            "candidate_probe_ids": unique_ids,
        }
    if len(unique_ids) == 1:
        return {
            "status": "selected",
            "policy": "explicit_or_single_probe",
            "selected_probe_id": unique_ids[0],
            "reason": "single_valid_probe",
            "candidate_probe_ids": unique_ids,
        }
    return {
        "status": "probe_policy_unresolved",
        "policy": "unresolved",
        "selected_probe_id": None,
        "reason": (
            "multiple_valid_probes_without_explicit_id"
            if len(unique_ids) > 1
            else "no_valid_probes"
        ),
        "candidate_probe_ids": unique_ids,
    }


def _fetch_microarray_with_retries(
    probe_id: int,
    *,
    gene_symbol: str,
    settings: Settings,
    max_attempts: int,
    sleep_seconds: float,
) -> tuple[ToolResult, list[dict[str, Any]]]:
    """Per-probe microarray_expression with Allen transient-failure retries."""
    attempts: list[dict[str, Any]] = []
    result: ToolResult | None = None
    allowed = max(1, int(max_attempts))
    pause = max(0.0, float(sleep_seconds))
    for attempt in range(1, allowed + 1):
        result = allen_brain.microarray_expression(
            probe_id, gene_symbol=gene_symbol, settings=settings
        )
        attempts.append(
            {
                "attempt": attempt,
                "success": result.success,
                "error_type": result.error_type,
                "error_message": result.error_message,
                "status_code": result.status_code,
                "request_url": result.request_url,
            }
        )
        if result.success:
            break
        if (
            not allen_brain._is_transient_expression_failure(result)
            or attempt >= allowed
        ):
            break
        if pause > 0:
            time.sleep(pause)
    assert result is not None
    return result, attempts


def _all_group_prefixes(
    groups: Sequence[tuple[str, tuple[str, ...]]],
) -> tuple[str, ...]:
    prefixes: list[str] = []
    seen: set[str] = set()
    for _, group_prefixes in groups:
        for prefix in group_prefixes:
            key = str(prefix).lower()
            if key not in seen:
                seen.add(key)
                prefixes.append(key)
    return tuple(prefixes)


def select_replicate_columns(
    column_names: Sequence[str],
    *,
    allowed_prefixes: Sequence[str],
) -> dict[str, Any]:
    """Select replicate columns that fully match ``prefix + integer``.

    Accepted examples: ``astrocytes_fetal_1``, ``microglla_3``,
    ``microglia_macrophage_2``.

    Rejected examples: ``oligodendrocytes_average_count``,
    ``oligodendrocytes_standard_deviation``, metadata columns, and any
    prefix-matching name without a trailing integer replicate suffix.
    """
    prefixes = [str(p).lower() for p in allowed_prefixes if str(p).strip()]
    # Longest prefix first so astrocytes_fetal_ beats astrocytes_.
    prefixes_sorted = sorted(prefixes, key=len, reverse=True)
    selected: list[str] = []
    excluded: list[dict[str, str]] = []
    seen_selected: set[str] = set()

    for raw_name in column_names:
        name = str(raw_name or "").strip()
        if not name:
            continue
        lower = name.lower()
        if lower in _SUMMARY_COLUMN_NAMES:
            excluded.append({"column": name, "reason": "metadata_column"})
            continue
        if lower.endswith("_average_count") or lower.endswith("_standard_deviation"):
            excluded.append({"column": name, "reason": "summary_statistic_column"})
            continue
        matched_prefix: str | None = None
        for prefix in prefixes_sorted:
            if not lower.startswith(prefix):
                continue
            remainder = lower[len(prefix) :]
            if remainder.isdigit() and remainder != "":
                matched_prefix = prefix
                break
            # Prefix matched but not a pure integer suffix.
            matched_prefix = None
            excluded.append(
                {
                    "column": name,
                    "reason": "prefix_without_numeric_replicate_suffix",
                }
            )
            break
        if matched_prefix is None:
            # Only record exclusion once; if already excluded above, skip.
            if not any(e["column"] == name for e in excluded):
                # Columns unrelated to cell-type prefixes are ignored quietly
                # unless they look like a near-miss (contain underscore digits).
                if any(lower.startswith(p) for p in prefixes_sorted):
                    pass  # already recorded
                else:
                    excluded.append({"column": name, "reason": "no_allowed_prefix"})
            continue
        if name not in seen_selected:
            seen_selected.add(name)
            selected.append(name)

    return {
        "selected": selected,
        "excluded": excluded,
        "allowed_prefixes": list(prefixes_sorted),
    }


def _parse_finite_nonnegative(raw: Any) -> float | None:
    """Return a finite nonnegative float, else None (no silent zero)."""
    if raw is None or raw == "":
        return None
    try:
        number = float(raw)
    except (TypeError, ValueError):
        return None
    if not math.isfinite(number) or number < 0:
        return None
    return number


def group_celltype_expression(
    row: dict[str, Any],
    *,
    groups: Sequence[tuple[str, tuple[str, ...]]],
) -> dict[str, Any]:
    """Mean ± SEM (ddof=1) per display group; n=1 yields no error bar.

    Only columns accepted by :func:`select_replicate_columns` contribute.
    Negative or nonfinite replicate values are excluded with audit reasons.
    """
    prefixes = _all_group_prefixes(groups)
    selection = select_replicate_columns(list(row.keys()), allowed_prefixes=prefixes)
    selected_set = set(selection["selected"])
    excluded_values: list[dict[str, Any]] = list(selection["excluded"])

    group_stats: list[dict[str, Any]] = []
    microglia_prefix_matched: str | None = None
    used_keys: set[str] = set()
    for label, group_prefixes in groups:
        matched: list[tuple[str, float]] = []
        for key in selection["selected"]:
            key_l = key.lower()
            for prefix in group_prefixes:
                prefix_l = str(prefix).lower()
                if not key_l.startswith(prefix_l):
                    continue
                remainder = key_l[len(prefix_l) :]
                if not remainder.isdigit():
                    continue
                number = _parse_finite_nonnegative(row.get(key))
                if number is None:
                    excluded_values.append(
                        {
                            "column": key,
                            "reason": "negative_or_nonfinite_value",
                            "raw": row.get(key),
                        }
                    )
                    break
                matched.append((key, number))
                used_keys.add(key)
                if "microgl" in prefix_l or "microglla" in prefix_l:
                    microglia_prefix_matched = prefix_l
                break
        nums = [v for _, v in matched]
        if not nums:
            group_stats.append(
                {
                    "label": label,
                    "mean_fpkm": 0.0,
                    "sem_fpkm": None,
                    "n": 0,
                    "columns": [],
                }
            )
            continue
        mean = float(statistics.mean(nums))
        if len(nums) >= 2:
            sem = float(statistics.stdev(nums) / math.sqrt(len(nums)))
        else:
            sem = None
        group_stats.append(
            {
                "label": label,
                "mean_fpkm": mean,
                "sem_fpkm": sem,
                "n": len(nums),
                "columns": [k for k, _ in matched],
            }
        )
    return {
        "groups": group_stats,
        "microglia_prefix_matched": microglia_prefix_matched,
        "matched_column_count": len(used_keys),
        "selected_replicate_columns": list(selection["selected"]),
        "excluded_columns": excluded_values,
        "selected_column_set_size": len(selected_set),
    }


def mouse_average_tpm_from_matrix(
    raw_csv: str,
    gene_symbol: str,
) -> dict[str, Any]:
    """Full-matrix FPKM→TPM using only validated mouse replicate columns.

    Fail-closed rules:
    - exactly one accepted mouse gene row (duplicates rejected)
    - target values must be finite and nonnegative
    - malformed/negative/nonfinite non-target cells are skipped from the
      denominator under ``_MOUSE_TPM_MALFORMED_ROW_POLICY`` (never coerced to 0)
    - a sample fails when its denominator is zero, negative, or nonfinite
    """
    rows = brainrnaseq.parse_csv(raw_csv)
    if not rows:
        return {
            "success": False,
            "error_type": "empty_csv",
            "error_message": "Mouse BrainRNASeq CSV has no rows",
        }

    header_keys: list[str] = []
    seen_keys: set[str] = set()
    for row in rows:
        for key in row:
            key_s = str(key)
            if key_s not in seen_keys:
                seen_keys.add(key_s)
                header_keys.append(key_s)

    prefixes = _all_group_prefixes(MOUSE_CELLTYPE_GROUPS)
    selection = select_replicate_columns(header_keys, allowed_prefixes=prefixes)
    replicate_cols = list(selection["selected"])
    if not replicate_cols:
        return {
            "success": False,
            "error_type": "no_replicate_columns",
            "error_message": "No validated mouse replicate columns for TPM conversion",
            "selected_replicate_columns": [],
            "excluded_columns": selection["excluded"],
        }

    matches = [
        row
        for row in rows
        if brainrnaseq.row_matches_gene(row, gene_symbol, species="mouse")
    ]
    if not matches:
        return {
            "success": False,
            "error_type": "gene_not_found",
            "error_message": f"Mouse gene {gene_symbol!r} not found in BrainRNASeq CSV",
            "selected_replicate_columns": replicate_cols,
            "excluded_columns": selection["excluded"],
        }
    if len(matches) > 1:
        return {
            "success": False,
            "error_type": "multiple_gene_matches",
            "error_message": (
                f"Mouse gene {gene_symbol!r} matched {len(matches)} rows; "
                "exactly one is required"
            ),
            "match_count": len(matches),
            "selected_replicate_columns": replicate_cols,
            "excluded_columns": selection["excluded"],
        }
    target_row = matches[0]

    sample_tpms: list[float] = []
    denominators: dict[str, float] = {}
    target_fpkms: dict[str, float] = {}
    target_tpms: dict[str, float] = {}
    failed_samples: list[dict[str, Any]] = []
    skipped_cells: list[dict[str, Any]] = []

    for key in replicate_cols:
        target_raw = target_row.get(key)
        target_fpkm = _parse_finite_nonnegative(target_raw)
        if target_fpkm is None:
            return {
                "success": False,
                "error_type": "invalid_target_value",
                "error_message": (
                    f"Target mouse FPKM for column {key!r} is missing, negative, "
                    "or nonfinite"
                ),
                "column": key,
                "raw": target_raw,
                "selected_replicate_columns": replicate_cols,
                "excluded_columns": selection["excluded"],
            }

        col_sum = 0.0
        for row in rows:
            number = _parse_finite_nonnegative(row.get(key))
            if number is None:
                skipped_cells.append(
                    {
                        "column": key,
                        "gene_id": row.get("gene_id") or row.get("id"),
                        "raw": row.get(key),
                        "policy": _MOUSE_TPM_MALFORMED_ROW_POLICY,
                    }
                )
                continue
            col_sum += number

        if not math.isfinite(col_sum) or col_sum <= 0:
            failed_samples.append(
                {
                    "column": key,
                    "denominator": col_sum,
                    "reason": "zero_negative_or_nonfinite_denominator",
                }
            )
            continue

        tpm = target_fpkm / col_sum * 1_000_000.0
        if not math.isfinite(tpm):
            failed_samples.append(
                {
                    "column": key,
                    "denominator": col_sum,
                    "reason": "nonfinite_tpm",
                }
            )
            continue

        denominators[key] = float(col_sum)
        target_fpkms[key] = float(target_fpkm)
        target_tpms[key] = float(tpm)
        sample_tpms.append(float(tpm))

    if not sample_tpms:
        return {
            "success": False,
            "error_type": "no_valid_samples",
            "error_message": "No mouse replicate columns produced a valid TPM",
            "selected_replicate_columns": replicate_cols,
            "excluded_columns": selection["excluded"],
            "failed_samples": failed_samples,
            "skipped_cells_count": len(skipped_cells),
            "malformed_row_policy": _MOUSE_TPM_MALFORMED_ROW_POLICY,
        }

    return {
        "success": True,
        "mean_tpm": float(statistics.mean(sample_tpms)),
        "median_tpm": float(statistics.median(sample_tpms)),
        "minimum_tpm": float(min(sample_tpms)),
        "maximum_tpm": float(max(sample_tpms)),
        "sample_count": len(sample_tpms),
        "unit": "TPM",
        "gene_symbol": target_row.get("gene_id") or gene_symbol,
        "conversion": "full_matrix_columnwise_fpkm_to_tpm",
        "conversion_version": "mouse_tpm_v2_replicate_columns",
        "selected_replicate_columns": replicate_cols,
        "excluded_columns": selection["excluded"],
        "denominators": denominators,
        "target_fpkm_by_column": target_fpkms,
        "target_tpm_by_column": target_tpms,
        "failed_samples": failed_samples,
        "skipped_cells_count": len(skipped_cells),
        "malformed_row_policy": _MOUSE_TPM_MALFORMED_ROW_POLICY,
    }


def _draw_celltype_panel(
    ax: Any,
    *,
    symbol: str,
    species_label: str,
    groups: Sequence[dict[str, Any]] | None,
    color: str,
    unavailable_message: str,
) -> str:
    """Draw one panel; return panel_status ``success`` or ``unavailable``."""
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)
    if not groups:
        ax.set_title(f"{symbol} - {species_label}", fontsize=11, fontweight="bold", pad=6)
        ax.text(
            0.5,
            0.5,
            unavailable_message,
            transform=ax.transAxes,
            ha="center",
            va="center",
            fontsize=9,
            wrap=True,
        )
        ax.set_xticks([])
        ax.set_yticks([])
        return "unavailable"

    labels = [str(g.get("label") or "") for g in groups]
    means = [float(g.get("mean_fpkm") or 0.0) for g in groups]
    x = list(range(len(labels)))
    bars = ax.bar(x, means, color=color, edgecolor="#444444", linewidth=0.4)
    yerr = []
    for g in groups:
        sem = g.get("sem_fpkm")
        yerr.append(float(sem) if sem is not None else 0.0)
    if any(g.get("sem_fpkm") is not None for g in groups):
        ax.errorbar(
            x,
            means,
            yerr=yerr,
            fmt="none",
            ecolor="black",
            elinewidth=1.0,
            capsize=3,
        )
    ax.set_title(f"{symbol} - {species_label}", fontsize=11, fontweight="bold", pad=6)
    ax.set_ylabel("FPKM", fontsize=9)
    ax.set_xticks(x)
    ax.set_xticklabels(labels, rotation=35, ha="right", fontsize=7.5)
    ax.set_ylim(bottom=0)
    _ = bars
    return "success"


def render_celltype_figure_png(
    *,
    human_symbol: str,
    mouse_symbol: str,
    human_groups: Sequence[dict[str, Any]] | None,
    mouse_groups: Sequence[dict[str, Any]] | None,
    dpi: int = 180,
) -> tuple[bytes, dict[str, str]]:
    """Combined vertically stacked human (pink) / mouse (blue) FPKM bar figure.

    Either panel may be ``None`` (unavailable message). Returns PNG bytes and
    ``panel_status`` with ``human`` / ``mouse`` ∈ {success, unavailable}.
    """
    import matplotlib

    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    fig, axes = plt.subplots(2, 1, figsize=FIGURE_FIGSIZE, dpi=dpi)
    human_status = _draw_celltype_panel(
        axes[0],
        symbol=human_symbol,
        species_label="Homo sapiens",
        groups=human_groups,
        color=HUMAN_BAR_COLOR,
        unavailable_message=UNAVAILABLE_PANEL_MESSAGE_HUMAN,
    )
    mouse_status = _draw_celltype_panel(
        axes[1],
        symbol=mouse_symbol,
        species_label="Mus musculus",
        groups=mouse_groups,
        color=MOUSE_BAR_COLOR,
        unavailable_message=UNAVAILABLE_PANEL_MESSAGE_MOUSE,
    )
    fig.subplots_adjust(hspace=0.55, top=0.94, bottom=0.14, left=0.10, right=0.98)
    buf = io.BytesIO()
    fig.savefig(buf, format="png", dpi=dpi, bbox_inches="tight", pad_inches=0.15)
    plt.close(fig)
    return buf.getvalue(), {"human": human_status, "mouse": mouse_status}


def figure_status_from_panels(panel_status: dict[str, str]) -> str:
    """Map panel success flags to a figure rendering status string."""
    human_ok = panel_status.get("human") == "success"
    mouse_ok = panel_status.get("mouse") == "success"
    if human_ok and mouse_ok:
        return "success_two_panels"
    if human_ok:
        return "success_human_only"
    if mouse_ok:
        return "success_mouse_only"
    return "unavailable_no_panels"


def _download_audit_fields(tr: ToolResult) -> dict[str, Any]:
    data = tr.data if isinstance(tr.data, dict) else {}
    return {
        "success": tr.success,
        "error_type": tr.error_type,
        "error_message": tr.error_message,
        "status_code": tr.status_code,
        "request_url": tr.request_url,
        "final_url": data.get("final_url") or tr.request_url,
        "content_type": data.get("content_type"),
        "byte_size": data.get("byte_size"),
        "sha256": data.get("sha256"),
        "retrieval_method": data.get("retrieval_method"),
        "browser_channel": data.get("browser_channel"),
        "capture_via": data.get("capture_via"),
    }


def _persist_brainrnaseq_csv_download(
    *,
    tr: ToolResult,
    dossier_run_id: str,
    gene_symbol: str,
    settings: Settings,
    persist_db: bool,
    filename_hint: str,
    species: str,
    query_symbol: str | None = None,
) -> tuple[Any, dict[str, Any] | None, str]:
    """Persist ApiRun (+ raw CSV on success). Returns api, meta, raw_csv text."""
    raw_csv = ""
    if tr.success and isinstance(tr.data, dict):
        raw_csv = str(tr.data.get("raw_csv") or "")
    notes: dict[str, Any] = {
        "species": species,
        "retrieval_method": (
            (tr.data or {}).get("retrieval_method")
            if isinstance(tr.data, dict)
            else None
        ),
        "source_url": tr.request_url,
        "final_url": (
            (tr.data or {}).get("final_url")
            if isinstance(tr.data, dict)
            else tr.request_url
        ),
        "browser_channel": (
            (tr.data or {}).get("browser_channel")
            if isinstance(tr.data, dict)
            else None
        ),
        "sha256": (
            (tr.data or {}).get("sha256") if isinstance(tr.data, dict) else None
        ),
        "byte_size": (
            (tr.data or {}).get("byte_size") if isinstance(tr.data, dict) else None
        ),
    }
    if query_symbol is not None:
        notes["query_symbol"] = query_symbol
    persist_tr = (
        tr
        if not tr.success
        else tr.model_copy(
            update={
                "data": {
                    k: v
                    for k, v in (tr.data or {}).items()
                    if k != "raw_csv"
                }
                if isinstance(tr.data, dict)
                else tr.data
            }
        )
    )
    api, meta = _persist_tool_result_bytes(
        tr=persist_tr,
        dossier_run_id=dossier_run_id,
        gene_symbol=gene_symbol,
        settings=settings,
        persist_db=persist_db,
        filename_hint=filename_hint,
        extension="csv",
        media_type="text/csv",
        content=raw_csv.encode("utf-8") if tr.success else b"",
        notes=notes,
    )
    return api, meta, raw_csv


def _resolve_brainrnaseq_species_csv(
    *,
    species: str,
    gene_symbol: str,
    query_symbol: str,
    dossier_run_id: str,
    settings: Settings,
    persist_db: bool,
    api_runs: list,
    raw_meta: list,
) -> dict[str, Any]:
    """Direct httpx download, then browser fallback; keep ApiRuns separate."""
    species_lit: brainrnaseq.SpeciesChoice = (
        "mouse" if species == "mouse" else "human"
    )
    primary = brainrnaseq.download_csv(
        species_lit, gene_symbol=query_symbol, settings=settings
    )
    primary_api, primary_meta, primary_raw = _persist_brainrnaseq_csv_download(
        tr=primary,
        dossier_run_id=dossier_run_id,
        gene_symbol=gene_symbol,
        settings=settings,
        persist_db=persist_db,
        filename_hint=f"brainrnaseq-{species}-{slugify(query_symbol)}",
        species=species,
        query_symbol=query_symbol if species == "mouse" else None,
    )
    api_runs.append(primary_api)
    if primary_meta:
        raw_meta.append(primary_meta)

    audit: dict[str, Any] = {
        "download": {
            **_download_audit_fields(primary),
            "api_run_id": primary_api.id,
            "raw_artifact_id": primary_meta.get("id") if primary_meta else None,
            "primary": True,
        },
        "browser_fallback_attempted": False,
        "selected_retrieval_method": None,
        "query_symbol": query_symbol,
    }

    selected_tr = primary
    selected_api = primary_api
    selected_meta = primary_meta
    selected_raw = primary_raw

    if primary.success:
        audit["selected_retrieval_method"] = "httpx_direct"
    elif brainrnaseq._should_fallback_to_browser(primary):
        audit["browser_fallback_attempted"] = True
        browser = brainrnaseq.download_csv_via_browser(
            species_lit, gene_symbol=query_symbol, settings=settings
        )
        browser_api, browser_meta, browser_raw = _persist_brainrnaseq_csv_download(
            tr=browser,
            dossier_run_id=dossier_run_id,
            gene_symbol=gene_symbol,
            settings=settings,
            persist_db=persist_db,
            filename_hint=(
                f"brainrnaseq-{species}-browser-{slugify(query_symbol)}"
            ),
            species=species,
            query_symbol=query_symbol if species == "mouse" else None,
        )
        api_runs.append(browser_api)
        if browser_meta:
            raw_meta.append(browser_meta)
        audit["browser_fallback"] = {
            **_download_audit_fields(browser),
            "api_run_id": browser_api.id,
            "raw_artifact_id": browser_meta.get("id") if browser_meta else None,
        }
        if browser.success:
            selected_tr = browser
            selected_api = browser_api
            selected_meta = browser_meta
            selected_raw = browser_raw
            audit["selected_retrieval_method"] = "official_browser_download"
        else:
            audit["selected_retrieval_method"] = None
    else:
        audit["selected_retrieval_method"] = None

    return {
        "success": selected_tr.success,
        "tool_result": selected_tr,
        "api": selected_api,
        "meta": selected_meta,
        "raw_csv": selected_raw,
        "audit": audit,
        "primary_success": primary.success,
    }


def _resolve_mouse_symbol(
    state: DossierState,
    *,
    gene: str,
    settings: Settings,
    persist_db: bool,
    api_runs: list,
    raw_meta: list,
    audit: dict[str, Any],
) -> str | None:
    gene_ids = dict(state.get("gene_ids") or {})
    existing = str(gene_ids.get("mouse_symbol") or "").strip()
    if existing:
        audit["mouse_identity"] = {"source": "gene_ids", "mouse_symbol": existing}
        return existing

    results = fetch_species_identity_results(
        gene, settings=settings, skip_taxons={9606, 10116}
    )
    mouse_symbol: str | None = None
    for tr in results:
        api, meta = _persist_tool_result_json(
            tr=tr,
            dossier_run_id=state["dossier_run_id"],
            gene_symbol=gene,
            settings=settings,
            persist_db=persist_db,
            filename_hint=f"species-identity-{slugify(tr.endpoint_name)}",
        )
        api_runs.append(api)
        if meta:
            raw_meta.append(meta)
        if not tr.success or not isinstance(tr.data, dict):
            continue
        resolved = (
            tr.data.get("species_gene_symbol")
            or tr.data.get("resolved_symbol")
            or tr.data.get("symbol")
        )
        if resolved and str(resolved).strip():
            mouse_symbol = str(resolved).strip()
            # Prefer NCBI Gene mouse lookup when present.
            if "ncbi" in (tr.endpoint_name or "").lower() or tr.source_name == "NCBI Gene":
                break
    audit["mouse_identity"] = {
        "source": "species_identity_mouse_only",
        "mouse_symbol": mouse_symbol,
        "tool_result_count": len(results),
    }
    if mouse_symbol:
        gene_ids["mouse_symbol"] = mouse_symbol
        state["gene_ids"] = gene_ids
    return mouse_symbol


def node_generate_section_2b_derived_artifacts(
    state: DossierState,
    *,
    settings: Settings | None = None,
    persist_db: bool = True,
    transient: WorkflowTransientContext | None = None,
    config: Section2bConfig | None = None,
) -> DossierState:
    """Sole Section 2b network owner: Allen MA + donor RNA-seq + BrainRNASeq."""
    _ = transient
    if state.get("run_type") != "section_bundle" or "2b" not in (
        state.get("selected_section_keys") or []
    ):
        return state

    cfg = settings or get_settings()
    section_cfg = config or Section2bConfig()
    run_id = state["dossier_run_id"]
    gene = state["gene_symbol"]
    gene_ids = dict(state.get("gene_ids") or {})
    evidence = list(state.get("evidence_records") or [])
    api_runs = list(state.get("api_runs") or [])
    raw_meta = list(state.get("raw_artifacts") or [])
    errors = list(state.get("errors") or [])
    coverage_extra = list(state.get("coverage") or [])

    audit: dict[str, Any] = {
        "config": {
            "donor_well_known_file_ids": list(section_cfg.donor_well_known_file_ids),
            "exclude_rnaseq_technical_replicates": (
                section_cfg.exclude_rnaseq_technical_replicates
            ),
            "allen_probe_id": section_cfg.allen_probe_id,
            "probe_selection_policy": section_cfg.probe_selection_policy,
            "category_policy": section_cfg.category_policy,
            "plot_dpi": section_cfg.plot_dpi,
            "plot_version": PLOT_VERSION,
            "max_expression_attempts": section_cfg.max_expression_attempts,
            "retry_sleep_seconds": section_cfg.retry_sleep_seconds,
            "scale_detection_tolerances": allen_human_rnaseq.scale_detection_tolerances(),
        },
        "network_owner": "section_2b",
        "allen_microarray": {},
        "allen_rnaseq": {},
        "brainrnaseq": {},
        "retrieved_at": datetime.now(timezone.utc).isoformat(),
    }

    rendering = {
        "overall": "pending",
        "agilent": "pending",
        "human_rnaseq_tpm": "pending",
        "mouse_rnaseq_tpm": "pending",
        "celltype_figure": "pending",
        "categories": "threshold_policy_unresolved",
    }

    human_entrez = _normalize_entrez_gene_id(gene_ids.get("entrez_gene_id"))
    mouse_symbol = _resolve_mouse_symbol(
        state,
        gene=gene,
        settings=cfg,
        persist_db=persist_db,
        api_runs=api_runs,
        raw_meta=raw_meta,
        audit=audit,
    )

    # ------------------------------------------------------------------
    # Allen HumanMA microarray: probe_lookup once, then per-probe expression
    # ------------------------------------------------------------------
    probe_tr = allen_brain.probe_lookup(gene, settings=cfg)
    probe_api, probe_meta = _persist_tool_result_json(
        tr=probe_tr,
        dossier_run_id=run_id,
        gene_symbol=gene,
        settings=cfg,
        persist_db=persist_db,
        filename_hint=f"allen-probe-lookup-{slugify(gene)}",
    )
    api_runs.append(probe_api)
    if probe_meta:
        raw_meta.append(probe_meta)

    selected_agilent_mean: float | None = None
    selection_summary: dict[str, Any] = {
        "status": "probe_policy_unresolved",
        "selected_probe_id": None,
    }
    probe_summaries_evidence: list[dict[str, Any]] = []

    allen_ma_audit: dict[str, Any] = {
        "probe_lookup": {
            "success": probe_tr.success,
            "error_type": probe_tr.error_type,
            "error_message": probe_tr.error_message,
            "api_run_id": probe_api.id,
            "raw_artifact_id": probe_meta.get("id") if probe_meta else None,
        },
        "discovered_probe_count": 0,
        "validated_probe_count": 0,
        "requested_probe_count": 0,
        "successful_probe_count": 0,
        "failed_probe_ids": [],
        "expression_attempts": {},
    }

    if not probe_tr.success:
        rendering["agilent"] = "failed"
        coverage_extra.append(
            SourceCoverageResult(
                dossier_run_id=run_id,
                source_name=allen_brain.SOURCE_NAME,
                status=SourceStatus.failed,
                evidence_record_count=0,
                error_message=probe_tr.error_message or "Allen probe lookup failed",
                report_sections_supported=[SUBSECTION_2B],
            )
        )
    else:
        validated = validate_probe_lookup_rows(
            probe_tr.data,
            gene_symbol=gene,
            entrez_gene_id=human_entrez,
        )
        discovered = list(validated.get("discovered_probes") or [])
        valid_probes = list(validated.get("validated_probes") or [])
        allen_ma_audit["discovered_probe_count"] = len(discovered)
        allen_ma_audit["validated_probe_count"] = len(valid_probes)
        allen_ma_audit["discovered_probe_ids"] = [
            p.get("id") for p in discovered
        ]
        allen_ma_audit["validated_probe_ids"] = [p.get("id") for p in valid_probes]

        # Request expression for every validated probe (no hidden truncation).
        allen_ma_audit["requested_probe_count"] = len(valid_probes)
        expression_by_id: dict[int, dict[str, Any]] = {}
        failed_ids: list[int] = []
        for prow in valid_probes:
            pid = int(prow["id"])
            expr_tr, attempts = _fetch_microarray_with_retries(
                pid,
                gene_symbol=gene,
                settings=cfg,
                max_attempts=section_cfg.max_expression_attempts,
                sleep_seconds=section_cfg.retry_sleep_seconds,
            )
            allen_ma_audit["expression_attempts"][str(pid)] = attempts
            # Persist only the final attempt as the ApiRun/raw artifact for this probe.
            expr_api, expr_meta = _persist_tool_result_json(
                tr=expr_tr,
                dossier_run_id=run_id,
                gene_symbol=gene,
                settings=cfg,
                persist_db=persist_db,
                filename_hint=f"allen-microarray-expression-{pid}",
            )
            api_runs.append(expr_api)
            if expr_meta:
                raw_meta.append(expr_meta)

            parsed = (
                _mean_expression_level(
                    expr_tr.data,
                    gene_symbol=gene,
                    entrez_gene_id=human_entrez,
                )
                if expr_tr.success
                else {
                    "success": False,
                    "error_type": expr_tr.error_type or "expression_failed",
                }
            )
            if not expr_tr.success or not parsed.get("success"):
                failed_ids.append(pid)
                continue
            expression_by_id[pid] = {
                **parsed,
                "api_run_id": expr_api.id,
                "raw_artifact_id": expr_meta.get("id") if expr_meta else None,
                "probe_name": prow.get("name"),
            }
            compact = {
                "probe_id": pid,
                "probe_name": prow.get("name"),
                "gene_acronym": prow.get("gene_acronym"),
                "entrez_id": prow.get("entrez_id"),
                "mean_expression": parsed.get("mean_expression"),
                "sample_count": parsed.get("sample_count"),
                "unit": "Agilent intensity",
            }
            probe_summaries_evidence.append(compact)
            rec = _evidence(
                dossier_run_id=run_id,
                gene_symbol=gene,
                source_name=allen_brain.SOURCE_NAME,
                fact_type="allen_human_microarray_probe_summary",
                key=f"probe-{pid}",
                value=compact,
                display_text=(
                    f"{gene} Allen HumanMA probe {pid} mean expression is "
                    f"{parsed.get('mean_expression')}."
                ),
                api_run_id=expr_api.id,
                raw_artifact_id=expr_meta.get("id") if expr_meta else None,
            )
            _append_evidence(evidence, rec, persist_db=persist_db)

        allen_ma_audit["successful_probe_count"] = len(expression_by_id)
        allen_ma_audit["failed_probe_ids"] = failed_ids

        selection_summary = select_agilent_probe(
            valid_probes,
            allen_probe_id=section_cfg.allen_probe_id,
            policy=section_cfg.probe_selection_policy,
        )
        allen_ma_audit["selection"] = selection_summary
        selected_id = selection_summary.get("selected_probe_id")
        if (
            selection_summary.get("status") == "selected"
            and selected_id is not None
            and int(selected_id) in expression_by_id
        ):
            selected_agilent_mean = float(
                expression_by_id[int(selected_id)]["mean_expression"]
            )
            rendering["agilent"] = "success"
            sel_rec = _evidence(
                dossier_run_id=run_id,
                gene_symbol=gene,
                source_name=allen_brain.SOURCE_NAME,
                fact_type="allen_human_microarray_selection_summary",
                key="selection",
                value={
                    **selection_summary,
                    "mean_expression": selected_agilent_mean,
                    "unit": "Agilent intensity",
                },
                display_text=(
                    f"{gene} Allen Agilent mean expression is {selected_agilent_mean}."
                ),
                api_run_id=expression_by_id[int(selected_id)].get("api_run_id"),
                raw_artifact_id=expression_by_id[int(selected_id)].get(
                    "raw_artifact_id"
                ),
            )
            _append_evidence(evidence, sel_rec, persist_db=persist_db)
        else:
            rendering["agilent"] = "unavailable"
            sel_rec = _evidence(
                dossier_run_id=run_id,
                gene_symbol=gene,
                source_name=allen_brain.SOURCE_NAME,
                fact_type="allen_human_microarray_selection_summary",
                key="selection",
                value={
                    **selection_summary,
                    "mean_expression": None,
                    "unit": "Agilent intensity",
                },
                display_text=(
                    f"{gene} Allen Agilent probe selection is unresolved."
                ),
                api_run_id=probe_api.id,
                raw_artifact_id=probe_meta.get("id") if probe_meta else None,
            )
            _append_evidence(evidence, sel_rec, persist_db=persist_db)

    audit["allen_microarray"] = allen_ma_audit

    # ------------------------------------------------------------------
    # Allen two-donor RNA-seq TPM
    # ------------------------------------------------------------------
    donor_results: list[dict[str, Any]] = []
    donor_audits: list[dict[str, Any]] = []
    for donor_id in section_cfg.donor_well_known_file_ids:
        zip_tr = allen_human_rnaseq.download_donor_zip(
            donor_id, gene_symbol=gene, settings=cfg
        )
        content = b""
        if zip_tr.success and isinstance(zip_tr.data, dict):
            content = zip_tr.data.get("content") or b""
        # Persist raw ZIP without embedding bytes into ApiRun JSON notes heavily.
        persist_tr = zip_tr.model_copy(
            update={
                "data": {
                    k: v
                    for k, v in (zip_tr.data or {}).items()
                    if k != "content"
                }
                if isinstance(zip_tr.data, dict)
                else zip_tr.data
            }
        )
        zip_api, zip_meta = _persist_tool_result_bytes(
            tr=persist_tr if zip_tr.success else zip_tr,
            dossier_run_id=run_id,
            gene_symbol=gene,
            settings=cfg,
            persist_db=persist_db,
            filename_hint=f"allen-rnaseq-donor-{donor_id}",
            extension="zip",
            media_type="application/zip",
            content=content if zip_tr.success else b"",
            notes={
                "well_known_file_id": donor_id,
                "sha256": (
                    zip_tr.data.get("sha256")
                    if isinstance(zip_tr.data, dict)
                    else None
                ),
            },
        )
        if not zip_tr.success:
            # Ensure failure ApiRun is stored.
            if zip_api.id not in {a.id for a in api_runs}:
                api_runs.append(zip_api)
            donor_audits.append(
                {
                    "well_known_file_id": donor_id,
                    "success": False,
                    "error_type": zip_tr.error_type,
                    "error_message": zip_tr.error_message,
                    "api_run_id": zip_api.id,
                }
            )
            donor_results.append({"success": False, "well_known_file_id": donor_id})
            continue

        api_runs.append(zip_api)
        if zip_meta:
            raw_meta.append(zip_meta)

        parsed = allen_human_rnaseq.parse_donor_package(
            content,
            gene_symbol=gene,
            entrez_gene_id=human_entrez,
            well_known_file_id=donor_id,
            exclude_technical_replicates=(
                section_cfg.exclude_rnaseq_technical_replicates
            ),
        )
        donor_audit = {
            "well_known_file_id": donor_id,
            "success": bool(parsed.get("success")),
            "error_type": parsed.get("error_type"),
            "error_message": parsed.get("error_message"),
            "brain_identity": parsed.get("brain_identity"),
            "retained_sample_count": parsed.get("retained_sample_count"),
            "technical_replicate_count": parsed.get("technical_replicate_count"),
            "mean_tpm": parsed.get("mean_tpm"),
            "scale_detection": parsed.get("scale_detection"),
            "sample_column_sum_diagnostics": parsed.get(
                "sample_column_sum_diagnostics"
            ),
            "api_run_id": zip_api.id,
            "raw_artifact_id": zip_meta.get("id") if zip_meta else None,
            "validated_only_members_present": parsed.get(
                "validated_only_members_present"
            ),
        }
        # Persist derived members parented to ZIP raw artifact.
        if parsed.get("success") and zip_meta:
            parent_id = zip_meta.get("id")
            for member_name, member_bytes in (
                parsed.get("derived_members") or {}
            ).items():
                ext = "txt" if member_name.endswith(".txt") else "csv"
                media = "text/plain" if ext == "txt" else "text/csv"
                try:
                    der_art, der_meta = _persist_artifact_bytes(
                        dossier_run_id=run_id,
                        source_name=allen_human_rnaseq.SOURCE_NAME,
                        content=member_bytes,
                        extension=ext,
                        artifact_type=ext,
                        filename_hint=f"allen-rnaseq-donor-{donor_id}-{slugify(member_name)}",
                        settings=cfg,
                        api_run=None,
                        persist_db=persist_db,
                        notes={
                            "artifact_class": "derived",
                            "artifact_origin": "allen_human_rnaseq_unzip",
                            "artifact_role": member_name,
                            "parent_raw_artifact_ids": [parent_id],
                            "well_known_file_id": donor_id,
                            "retrieval_method": "unzip_derived",
                        },
                        validate=lambda b, m=media: _validate_bytes(b, media_type=m),
                    )
                    raw_meta.append(der_meta)
                    donor_audit.setdefault("derived_artifact_ids", {})[
                        member_name
                    ] = der_art.id
                except Exception as exc:  # noqa: BLE001
                    logger.warning(
                        "Failed to persist derived %s for donor %s: %s",
                        member_name,
                        donor_id,
                        exc,
                    )
        donor_audits.append(donor_audit)
        donor_results.append(parsed)

        if parsed.get("success"):
            donor_rec = _evidence(
                dossier_run_id=run_id,
                gene_symbol=gene,
                source_name=allen_human_rnaseq.SOURCE_NAME,
                fact_type="allen_human_rnaseq_donor_summary",
                key=f"donor-{donor_id}",
                value={
                    "well_known_file_id": donor_id,
                    "brain_identity": parsed.get("brain_identity"),
                    "retained_sample_count": parsed.get("retained_sample_count"),
                    "mean_tpm": parsed.get("mean_tpm"),
                    "unit": "TPM",
                    "scale_mode": (parsed.get("scale_detection") or {}).get(
                        "scale_mode"
                    ),
                },
                display_text=(
                    f"{gene} Allen donor {donor_id} mean TPM is {parsed.get('mean_tpm')}."
                ),
                api_run_id=zip_api.id,
                raw_artifact_id=zip_meta.get("id") if zip_meta else None,
            )
            _append_evidence(evidence, donor_rec, persist_db=persist_db)

    pooled = allen_human_rnaseq.pooled_mean_across_donors(donor_results)
    human_tpm: float | None = None
    if pooled.get("success"):
        human_tpm = float(pooled["mean_tpm"])
        rendering["human_rnaseq_tpm"] = "success"
        pool_rec = _evidence(
            dossier_run_id=run_id,
            gene_symbol=gene,
            source_name=allen_human_rnaseq.SOURCE_NAME,
            fact_type="allen_human_rnaseq_pooled_summary",
            key="pooled",
            value={
                **{k: v for k, v in pooled.items() if k != "success"},
            },
            display_text=f"{gene} Allen pooled human brain TPM is {human_tpm}.",
            api_run_id=(donor_audits[0].get("api_run_id") if donor_audits else None),
            raw_artifact_id=(
                donor_audits[0].get("raw_artifact_id") if donor_audits else None
            ),
        )
        _append_evidence(evidence, pool_rec, persist_db=persist_db)
    else:
        rendering["human_rnaseq_tpm"] = (
            "unavailable"
            if any(r.get("success") for r in donor_results)
            else "failed"
        )
        coverage_extra.append(
            SourceCoverageResult(
                dossier_run_id=run_id,
                source_name=allen_human_rnaseq.SOURCE_NAME,
                status=SourceStatus.failed,
                evidence_record_count=0,
                error_message=pooled.get("error_message")
                or "Allen human RNA-seq TPM unavailable",
                report_sections_supported=[SUBSECTION_2B],
            )
        )

    audit["allen_rnaseq"] = {
        "donors": donor_audits,
        "pooled": pooled,
    }

    # ------------------------------------------------------------------
    # BrainRNASeq human + mouse (direct download, then browser fallback)
    # ------------------------------------------------------------------
    human_groups: list[dict[str, Any]] | None = None
    mouse_groups: list[dict[str, Any]] | None = None
    mouse_tpm: float | None = None
    human_meta: dict[str, Any] | None = None
    mouse_meta: dict[str, Any] | None = None
    human_api_id: str | None = None
    mouse_api_id: str | None = None
    brs_audit: dict[str, Any] = {"human": {}, "mouse": {}}

    human_resolved = _resolve_brainrnaseq_species_csv(
        species="human",
        gene_symbol=gene,
        query_symbol=gene,
        dossier_run_id=run_id,
        settings=cfg,
        persist_db=persist_db,
        api_runs=api_runs,
        raw_meta=raw_meta,
    )
    human_meta = human_resolved.get("meta")
    human_api = human_resolved["api"]
    human_api_id = human_api.id
    human_raw = str(human_resolved.get("raw_csv") or "")
    brs_audit["human"] = dict(human_resolved.get("audit") or {})

    if human_resolved.get("success"):
        human_dl = human_resolved["tool_result"]
        human_expr = brainrnaseq.expression_from_raw_csv(
            human_raw,
            gene,
            species="human",
            request_url=human_dl.request_url,
            content_type=(
                human_dl.data.get("content_type")
                if isinstance(human_dl.data, dict)
                else None
            ),
            status_code=human_dl.status_code,
        )
        matched = []
        if human_expr.success and isinstance(human_expr.data, dict):
            matched = list(human_expr.data.get("matched_rows") or [])
        brs_audit["human"]["match_count"] = len(matched)
        if len(matched) == 1:
            grouped = group_celltype_expression(
                matched[0], groups=HUMAN_CELLTYPE_GROUPS
            )
            human_groups = list(grouped["groups"])
            brs_audit["human"]["grouping"] = {
                "microglia_prefix_matched": grouped.get("microglia_prefix_matched"),
                "matched_column_count": grouped.get("matched_column_count"),
                "selected_replicate_columns": grouped.get(
                    "selected_replicate_columns"
                ),
                "excluded_columns": grouped.get("excluded_columns"),
                "groups": [
                    {
                        "label": g.get("label"),
                        "mean_fpkm": g.get("mean_fpkm"),
                        "sem_fpkm": g.get("sem_fpkm"),
                        "n": g.get("n"),
                    }
                    for g in human_groups
                ],
            }
            human_ct_rec = _evidence(
                dossier_run_id=run_id,
                gene_symbol=gene,
                source_name=brainrnaseq.SOURCE_NAME,
                fact_type="brainrnaseq_human_celltype_summary",
                key="human-celltype",
                value={
                    "gene_symbol": gene,
                    "groups": human_groups,
                    "unit": "FPKM",
                    "microglia_prefix_matched": grouped.get(
                        "microglia_prefix_matched"
                    ),
                },
                display_text=f"{gene} BrainRNASeq human cell-type FPKM summary.",
                api_run_id=human_api_id,
                raw_artifact_id=human_meta.get("id") if human_meta else None,
            )
            _append_evidence(evidence, human_ct_rec, persist_db=persist_db)
        else:
            brs_audit["human"]["error"] = (
                f"expected exactly one human row; got {len(matched)}"
            )
    else:
        coverage_extra.append(
            SourceCoverageResult(
                dossier_run_id=run_id,
                source_name=brainrnaseq.SOURCE_NAME,
                status=SourceStatus.failed,
                evidence_record_count=0,
                error_message=(
                    (human_resolved.get("tool_result").error_message if human_resolved.get("tool_result") else None)
                    or "BrainRNASeq human CSV download failed"
                ),
                report_sections_supported=[SUBSECTION_2B],
            )
        )

    # Mouse CSV
    mouse_query = mouse_symbol or gene
    mouse_resolved = _resolve_brainrnaseq_species_csv(
        species="mouse",
        gene_symbol=gene,
        query_symbol=mouse_query,
        dossier_run_id=run_id,
        settings=cfg,
        persist_db=persist_db,
        api_runs=api_runs,
        raw_meta=raw_meta,
    )
    mouse_meta = mouse_resolved.get("meta")
    mouse_api = mouse_resolved["api"]
    mouse_api_id = mouse_api.id
    mouse_raw = str(mouse_resolved.get("raw_csv") or "")
    brs_audit["mouse"] = dict(mouse_resolved.get("audit") or {})
    brs_audit["mouse"]["query_symbol"] = mouse_query

    if mouse_resolved.get("success"):
        mouse_dl = mouse_resolved["tool_result"]
        mouse_expr = brainrnaseq.expression_from_raw_csv(
            mouse_raw,
            mouse_query,
            species="mouse",
            request_url=mouse_dl.request_url,
            content_type=(
                mouse_dl.data.get("content_type")
                if isinstance(mouse_dl.data, dict)
                else None
            ),
            status_code=mouse_dl.status_code,
        )
        matched_m = []
        if mouse_expr.success and isinstance(mouse_expr.data, dict):
            matched_m = list(mouse_expr.data.get("matched_rows") or [])
        brs_audit["mouse"]["match_count"] = len(matched_m)
        if len(matched_m) == 1:
            grouped_m = group_celltype_expression(
                matched_m[0], groups=MOUSE_CELLTYPE_GROUPS
            )
            mouse_groups = list(grouped_m["groups"])
            brs_audit["mouse"]["grouping"] = {
                "microglia_prefix_matched": grouped_m.get("microglia_prefix_matched"),
                "matched_column_count": grouped_m.get("matched_column_count"),
                "selected_replicate_columns": grouped_m.get(
                    "selected_replicate_columns"
                ),
                "excluded_columns": grouped_m.get("excluded_columns"),
                "groups": [
                    {
                        "label": g.get("label"),
                        "mean_fpkm": g.get("mean_fpkm"),
                        "sem_fpkm": g.get("sem_fpkm"),
                        "n": g.get("n"),
                    }
                    for g in mouse_groups
                ],
            }
            mouse_ct_rec = _evidence(
                dossier_run_id=run_id,
                gene_symbol=gene,
                source_name=brainrnaseq.SOURCE_NAME,
                fact_type="brainrnaseq_mouse_celltype_summary",
                key="mouse-celltype",
                value={
                    "gene_symbol": mouse_query,
                    "groups": mouse_groups,
                    "unit": "FPKM",
                    "microglia_prefix_matched": grouped_m.get(
                        "microglia_prefix_matched"
                    ),
                },
                display_text=(
                    f"{mouse_query} BrainRNASeq mouse cell-type FPKM summary."
                ),
                api_run_id=mouse_api_id,
                raw_artifact_id=mouse_meta.get("id") if mouse_meta else None,
                organism="Mus musculus",
                taxon_id=10090,
            )
            _append_evidence(evidence, mouse_ct_rec, persist_db=persist_db)

            tpm_result = mouse_average_tpm_from_matrix(mouse_raw, mouse_query)
            brs_audit["mouse"]["average_tpm"] = {
                k: v for k, v in tpm_result.items() if k != "raw_csv"
            }
            if tpm_result.get("success"):
                mouse_tpm = float(tpm_result["mean_tpm"])
                rendering["mouse_rnaseq_tpm"] = "success"
                mouse_tpm_rec = _evidence(
                    dossier_run_id=run_id,
                    gene_symbol=gene,
                    source_name=brainrnaseq.SOURCE_NAME,
                    fact_type="brainrnaseq_mouse_average_tpm",
                    key="mouse-tpm",
                    value={
                        "gene_symbol": mouse_query,
                        "mean_tpm": mouse_tpm,
                        "median_tpm": tpm_result.get("median_tpm"),
                        "minimum_tpm": tpm_result.get("minimum_tpm"),
                        "maximum_tpm": tpm_result.get("maximum_tpm"),
                        "unit": "TPM",
                        "conversion": tpm_result.get("conversion"),
                        "conversion_version": tpm_result.get("conversion_version"),
                        "sample_count": tpm_result.get("sample_count"),
                        "selected_replicate_columns": tpm_result.get(
                            "selected_replicate_columns"
                        ),
                        "denominators": tpm_result.get("denominators"),
                    },
                    display_text=(
                        f"{mouse_query} BrainRNASeq mouse average TPM is {mouse_tpm}."
                    ),
                    api_run_id=mouse_api_id,
                    raw_artifact_id=mouse_meta.get("id") if mouse_meta else None,
                    organism="Mus musculus",
                    taxon_id=10090,
                )
                _append_evidence(evidence, mouse_tpm_rec, persist_db=persist_db)
            else:
                rendering["mouse_rnaseq_tpm"] = "failed"
        else:
            rendering["mouse_rnaseq_tpm"] = "failed"
            brs_audit["mouse"]["error"] = (
                f"expected exactly one mouse row; got {len(matched_m)}"
            )
    else:
        rendering["mouse_rnaseq_tpm"] = "failed"
        coverage_extra.append(
            SourceCoverageResult(
                dossier_run_id=run_id,
                source_name=brainrnaseq.SOURCE_NAME,
                status=SourceStatus.failed,
                evidence_record_count=0,
                error_message=(
                    (mouse_resolved.get("tool_result").error_message if mouse_resolved.get("tool_result") else None)
                    or "BrainRNASeq mouse CSV download failed"
                ),
                report_sections_supported=[SUBSECTION_2B],
            )
        )

    audit["brainrnaseq"] = brs_audit

    # ------------------------------------------------------------------
    # Combined cell-type figure (supports partial panels)
    # ------------------------------------------------------------------
    figure_path: str | None = None
    panel_status = {
        "human": "success" if human_groups else "unavailable",
        "mouse": "success" if mouse_groups else "unavailable",
    }
    if human_groups or mouse_groups:
        try:
            png, panel_status = render_celltype_figure_png(
                human_symbol=gene,
                mouse_symbol=mouse_symbol or mouse_query,
                human_groups=human_groups,
                mouse_groups=mouse_groups,
                dpi=section_cfg.plot_dpi,
            )
            fig_status = figure_status_from_panels(panel_status)
            parent_ids = [
                i
                for i in [
                    human_meta.get("id") if human_meta else None,
                    mouse_meta.get("id") if mouse_meta else None,
                ]
                if i and (
                    (i == (human_meta or {}).get("id") and human_groups)
                    or (i == (mouse_meta or {}).get("id") and mouse_groups)
                )
            ]
            fig_art, fig_meta = _persist_artifact_bytes(
                dossier_run_id=run_id,
                source_name=brainrnaseq.SOURCE_NAME,
                content=png,
                extension="png",
                artifact_type="png",
                filename_hint=f"section-2b-celltype-{slugify(gene)}",
                settings=cfg,
                api_run=None,
                persist_db=persist_db,
                notes={
                    "artifact_class": "derived",
                    "artifact_origin": "section_2b_matplotlib",
                    "artifact_role": "celltype_figure",
                    "retrieval_method": "derived_figure",
                    "derivation_type": "brainrnaseq_mean_sem_barplot",
                    "plot_version": PLOT_VERSION,
                    "panel_status": panel_status,
                    "figure_status": fig_status,
                    "parent_raw_artifact_ids": parent_ids,
                },
                validate=_validate_nonblank_image,
            )
            raw_meta.append(fig_meta)
            figure_path = fig_meta.get("relative_path") or fig_art.file_path
            rendering["celltype_figure"] = fig_status
            fig_rec = _evidence(
                dossier_run_id=run_id,
                gene_symbol=gene,
                source_name=brainrnaseq.SOURCE_NAME,
                fact_type="brainrnaseq_celltype_figure",
                key="celltype-figure",
                value={
                    "relative_path": fig_meta.get("relative_path"),
                    "sha256": fig_meta.get("content_hash") or fig_art.content_hash,
                    "width": fig_meta.get("width"),
                    "height": fig_meta.get("height"),
                    "byte_size": fig_meta.get("byte_size"),
                    "media_type": "image/png",
                    "artifact_class": "derived",
                    "derivation_type": "brainrnaseq_mean_sem_barplot",
                    "plot_version": PLOT_VERSION,
                    "human_bar_color": HUMAN_BAR_COLOR,
                    "mouse_bar_color": MOUSE_BAR_COLOR,
                    "panel_status": panel_status,
                    "figure_status": fig_status,
                    "figure_raw_artifact_id": fig_art.id,
                    "parent_raw_artifact_ids": parent_ids,
                },
                display_text=f"{gene} BrainRNASeq cell-type expression figure.",
                api_run_id=None,
                raw_artifact_id=fig_art.id,
            )
            _append_evidence(evidence, fig_rec, persist_db=persist_db)
            audit["celltype_figure"] = {
                "relative_path": fig_meta.get("relative_path"),
                "sha256": fig_meta.get("content_hash"),
                "width": fig_meta.get("width"),
                "height": fig_meta.get("height"),
                "byte_size": fig_meta.get("byte_size"),
                "panel_status": panel_status,
                "figure_status": fig_status,
                "plot_version": PLOT_VERSION,
                "derivation_type": "brainrnaseq_mean_sem_barplot",
                "api_run_id": None,
                "parent_raw_artifact_ids": parent_ids,
            }
        except Exception as exc:  # noqa: BLE001
            logger.exception("Section 2b cell-type figure failed for %s", gene)
            rendering["celltype_figure"] = "failed"
            errors.append(f"Section 2b cell-type figure failed: {exc}")
            audit["celltype_figure"] = {"error": str(exc), "panel_status": panel_status}
    else:
        rendering["celltype_figure"] = "unavailable_no_panels"
        audit["celltype_figure"] = {
            "figure_status": "unavailable_no_panels",
            "panel_status": panel_status,
        }

    # Categories always unresolved under locked policy.
    human_category = classify_expression(human_tpm)
    mouse_category = classify_expression(mouse_tpm)
    cat_rec = _evidence(
        dossier_run_id=run_id,
        gene_symbol=gene,
        source_name=brainrnaseq.SOURCE_NAME,
        fact_type="section_2b_category_status",
        key="categories",
        value={
            "policy": section_cfg.category_policy,
            "human_brain_expression_category": human_category,
            "mouse_brain_expression_category": mouse_category,
            "display": NOT_DETERMINED,
            "note": CATEGORY_NOTE,
        },
        display_text=CATEGORY_NOTE,
    )
    _append_evidence(evidence, cat_rec, persist_db=persist_db)

    summary_rec = _evidence(
        dossier_run_id=run_id,
        gene_symbol=gene,
        source_name=allen_brain.SOURCE_NAME,
        fact_type="section_2b_summary_table",
        key="summary",
        value={
            "gene_symbol": gene,
            "average_human_brain_agilent_expression": selected_agilent_mean,
            "average_human_brain_rnaseq_expression_tpm": human_tpm,
            "average_mouse_brain_rnaseq_expression_tpm": mouse_tpm,
            "human_brain_expression_category": NOT_DETERMINED,
            "mouse_brain_expression_category": NOT_DETERMINED,
            "category_policy": section_cfg.category_policy,
            "presentation_item_key": f"barres-{(gene or '').lower()}",
            "brainrnaseq_url": BRAINRNASEQ_HOME_URL,
        },
        display_text=f"{gene} Barres/Allen brain expression summary.",
    )
    _append_evidence(evidence, summary_rec, persist_db=persist_db)

    # Overall status:
    # - Categories unresolved alone do NOT force partial.
    # - SUCCESS requires: selected Agilent + two-donor human TPM + mouse TPM +
    #   two-panel cell-type figure.
    # - Partial when Agilent unresolved (e.g. multi-probe) OR any quantitative
    #   BrainRNASeq / figure failure (including single-panel figures).
    agilent_ok = rendering["agilent"] == "success" and selected_agilent_mean is not None
    human_ok = rendering["human_rnaseq_tpm"] == "success" and human_tpm is not None
    mouse_ok = rendering["mouse_rnaseq_tpm"] == "success" and mouse_tpm is not None
    figure_ok = rendering["celltype_figure"] == "success_two_panels"
    if agilent_ok and human_ok and mouse_ok and figure_ok:
        overall = "success"
    elif not any([agilent_ok, human_ok, mouse_ok, figure_ok]):
        overall = "empty"
    else:
        overall = "partial"
    rendering["overall"] = overall
    rendering["panel_status"] = panel_status

    section_status = {
        "rendering_status": rendering,
        "summary": {
            "gene_symbol": gene,
            "mouse_symbol": mouse_symbol or mouse_query,
            "average_human_brain_agilent_expression": selected_agilent_mean,
            "average_human_brain_rnaseq_expression_tpm": human_tpm,
            "average_mouse_brain_rnaseq_expression_tpm": mouse_tpm,
            "human_brain_expression_category": NOT_DETERMINED,
            "mouse_brain_expression_category": NOT_DETERMINED,
            "category_policy": section_cfg.category_policy,
            "probe_selection": selection_summary,
            "brainrnaseq_url": BRAINRNASEQ_HOME_URL,
            "figure_path": figure_path,
            "panel_status": panel_status,
            "presentation_item_key": f"barres-{(gene or '').lower()}",
        },
        "audit": audit,
    }

    return {
        **state,
        "gene_ids": dict(state.get("gene_ids") or gene_ids),
        "evidence_records": evidence,
        "api_runs": api_runs,
        "raw_artifacts": raw_meta,
        "errors": errors,
        "coverage": coverage_extra,
        "section_2b_status": section_status,
    }


__all__ = [
    "SECTION_EXPRESSION",
    "SUBSECTION_2B",
    "BRAINRNASEQ_HOME_URL",
    "BRAINRNASEQ_SOURCE_LINK_LABEL",
    "NOT_DETERMINED",
    "CATEGORY_NOTE",
    "HUMAN_CELLTYPE_GROUPS",
    "MOUSE_CELLTYPE_GROUPS",
    "SECTION_2B_PRODUCTION_DENYLIST",
    "Section2bConfig",
    "section_2b_intro_text",
    "section_2b_celltype_intro_text",
    "classify_expression",
    "format_numeric_cell",
    "validate_probe_lookup_rows",
    "select_agilent_probe",
    "select_replicate_columns",
    "group_celltype_expression",
    "mouse_average_tpm_from_matrix",
    "render_celltype_figure_png",
    "PLOT_VERSION",
    "figure_status_from_panels",
    "node_generate_section_2b_derived_artifacts",
]
